### ISSUE TITLE
GPA Unittests fail

### ISSUE THREAD

**Issue by Lehks** [Lehks/NostraUtils#64] opened 2018-06-05 09:17 UTC
File: mem_mngt/GeneralPurposeAllocator.hpp

With the new and improved error handling, the GPA's Unittests fail because too many errors are being pushed to the error handler.

**Comment by Dark-Delu** [comment] 2018-06-06 22:12
I could not reproduce this bug. 
The error count after the execution of the GPA unittests is 0. Current dev build merged and tested. 
Please provide further details and check for an error on your side.

**Comment by Lehks** [comment] 2018-06-07 10:02
The commit that is responsible for the error was not pushed yet. Sorry about that.

**Closed as completed** 2018-06-07 10:24 UTC
Labels: bug
